### ISSUE TITLE
Destroyed a block and crashed

### ISSUE THREAD

**Issue by NancalaStarry** [Snownee/Siege#1]
* Forge Version: 28.2.1
 * Mod Version: Siege-1.14.4-0.1.0

I'm sorry to disturb you. I have some crash reports here and I don't know what to do. When I tried destroying a block ,my game crashed.
Maybe you will maintain this mod later?XD

https://paste.ubuntu.com/p/fKQhCHK28s/
https://paste.ubuntu.com/p/kTTq8YpfHS/

**Comment by Snownee** [comment]
应该是Kiwi版本太新了，试试2.4.3

**Comment by NancalaStarry** [comment]
糟，被发现是中国人了awa、
换了2.4.3，没有问题了。
